name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"    # Trigger only on version tags like v1.0.0, v2.3.4, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required so hatch-vcs sees tags

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create venv
        run: uv venv .venv

      - name: Install hatch-vcs
        run: |
          . .venv/bin/activate
          uv pip install hatch-vcs

      - name: Build and Publish
        run: |
          . .venv/bin/activate
          uv build
          ls -lh dist  # Debug: List built files
          uv publish dist/* -- --yes

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
